name: E2E Tests

on:
  pull_request:
    branches:
      - master

jobs:
  e2e_chrome:
    runs-on: ubuntu-latest
    environment: stage
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v3

      - name: Run e2e tests @ Chrome 🧪
        uses: cypress-io/github-action@v3
        with:
          browser: chrome

  e2e_firefox:
    runs-on: ubuntu-latest
    environment: stage
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v3

      - name: Run e2e tests @ Firefox 🧪
        uses: cypress-io/github-action@v3
        with:
          browser: firefox
