name: Quality Assurance

on:
  pull_request:
    branches:
      - master

jobs:
  e2e_chrome:
    runs-on: ubuntu-latest
    environment: stage
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v3

      - name: Run e2e tests 🧪
        uses: cypress-io/github-action@v2
        with:
          browser: chrome

  e2e_firefox:
    runs-on: ubuntu-latest
    environment: stage
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v3

      - name: Run e2e tests 🧪
        uses: cypress-io/github-action@v2
        with:
          browser: firefox
